### ISSUE TITLE
default_input_file_names wrong paths

### ISSUE THREAD

**Issue by TheFlyingSushi** [alecjacobson/computer-graphics-raster-images#61]
in main.cpp, we have

```
    const std::vector<std::string> default_input_file_names = {
      "../data/dog.png",
      "../data/glasses.png",
      "../data/laser-beams.png",
      "../data/sparkles.png"
    };
```
However, my file path that i run from is in build/Debug, which is what the instructions said to do, which is evidently not the right paths. Should I change these file paths then? And should I submit them?

i.e.   "../../data/dog.png" works

**Comment by JackC92** [comment]
Based on the README file, which says only files in the src/ directory should be submitted, I would say it's not a problem since main.cpp is outside the directory.

**Comment by amacle** [comment]
The `raster` executable should be run from the `/build` directory according to the assignment. You will have to update your build output path so that the executable is built to this directory.

On Windows, this can be done in Visual Studio by right-clicking the `.sln` file, then selecting `Properties` and changing the appropriate field.
